### ISSUE TITLE
Ansible vault stopped working

### ISSUE THREAD

**Issue by andviro** [drone-plugins/drone-ansible#16]
Hello! 

Can you please add some cryptography library to the image? My builds suddenly started to fail with: `ERROR! ansible-vault requires either the cryptography library (preferred) or pycrypto in order to function.`

**Comment by tboerger** [comment]
Feel free to create a pull request which adds it to all Dockerfiles within the docker folder.

**Comment by xoxys** [comment]
Normally this should work while we install ansible with pip in the dockerfiles. Because `cryptography` is a required Python dependency for ansible and will be installed anyway. 

So I think there is something else "wrong".

**Comment by xoxys** [comment]
@tboerger maybe `cryptography` is also part of a package we are removing after `pip install ansible` in the dockerfile

**Comment by tboerger** [comment]
We are just removing dev packages, and we also did that before.

**Comment by andviro** [comment]
It seems that removal of `libressl-dev` breaks vault support somehow. I dont know how this problem never shown itself, but you can easily verify it by running `ansible-vault create` from within container. If this is ok, I can prepare a PR that fixes this.

**Comment by xoxys** [comment]
So right direction :) Yes please prepare a pull request for all docker files

**Comment by andviro** [comment]
please see PR #17. I'd also bumped up Ansible version to 2.7.9, if you don't mind.

**Comment by xoxys** [comment]
I was able to reproduce the issue. Reinstall libressl fixed the issue as described.

**Comment by tboerger** [comment]
Since #17 had been merged this can get closed :)
