### ISSUE TITLE
Ansible need rsync tool

### ISSUE THREAD

**Issue by kevinanew** [drone-plugins/drone-ansible#4]
When I use ansible [synchronize](https://docs.ansible.com/ansible/2.5/modules/synchronize_module.html) , I got an error like this:

```
FAILED! => {"changed": false, "msg": "Failed to find required executable rsync in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
```

**Comment by oliver-yu** [comment]
which rsync
/usr/bin/which: no rsync in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)

#yum install rsync -y
# which rsync      
/usr/bin/rsync

ok!

**Comment by tboerger** [comment]
What do you want to express with this comment?
