### ISSUE TITLE
add ansible collection install from the requirements

### ISSUE THREAD

**Issue by dkmatt0** [drone-plugins/drone-ansible#41]
Hello,

Here : https://github.com/drone-plugins/drone-ansible/blob/master/plugin.go#L210
With this function, ansible installs the roles. Could you add the launch of the `ansible collection install ....` command that will allow the installation of the collections from the requirements.yml?

Thanks you so much

**Comment by tboerger** [comment]
As you can see on https://github.com/drone-plugins/drone-ansible/pull/40#issuecomment-706717839 collections are already getting installed.

**Comment by dkmatt0** [comment]
Sorry my bad because on docker hub: plugins/ansible:latest => v2.1.0 but I need v3.

Thanks

**Comment by tboerger** [comment]
I missed that https://cloud.drone.io/drone-plugins/drone-ansible/81 failed which should update latest. I have triggered a rebuild to get also latest updated correctly.
