### ISSUE TITLE
Possibility to disable --force on galaxy install

### ISSUE THREAD

**Issue by hrenard** [drone-plugins/drone-ansible#43]
Hello,
I'm trying to speed up a pipeline used by developers (perfect isolation isn't the goal) but the slowest step is now downloading ansible galaxy collections. 
It would be very nice to have the possibility to disable the `--force` flag on ansible-galaxy install in order to mount a cache volume.

**Comment by tboerger** [comment]
In that case the easiest solution would be providing a pull request which adds an optional flag to disable the force flag. That's the best base to see if it fits well into the code.

**Comment by hrenard** [comment]
Okay, I'll try to submit one in the week. Is `disable_galaxy_overwrite` a good parameter name ?

**Comment by tboerger** [comment]
Maybe `galaxy_force` which defaults to `true`

**Comment by tboerger** [comment]
Solved via #44

**Comment by hrenard** [comment]
Will you update the documentation ? Or should I do it (and where) ?

**Comment by tboerger** [comment]
Would be great if you could also provide a pr to the plugin index.

**Comment by hrenard** [comment]
Sure, I had some trouble finding the index repo but I'll make a pr soon.
