### ISSUE TITLE
add ssh client

### ISSUE THREAD

**Issue by TankTheFrank** [drone-plugins/drone-ansible#8]
My rsync fails with 'Failed to find required executable ssh in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

This looks like a bug in ansible: https://github.com/ansible/ansible/issues/24705

Probably it's a easier to work around it by adding the ssh client. Besides, a ssh client is useful for all kind of things especially in a ansible/ci container.

**Comment by techknowlogick** [comment]
Are you able to disable fact gathering as a part of you ansible playbook? If not, I just pushed a PR that adds the openssh client. I’m on mobile so I can’t test the changes right now, but if you are able to build and test that the changes work then that would help PR get merged faster.

**Comment by tboerger** [comment]
I have merged the PR, it makes sense to add the openssh client to the docker image to get the synchronize component working, even if I personally don't use this component :).

You should be able to use the latest tag in a few minutes.
